### PR TITLE
Update subspec libs, bump major version

### PR DESCRIPTION
**Pull request by Kaspik**
- update bundler to 2.0+
- update other libs
- bump version to 0.1.0

### CODE REVIEW

**Comment by Kaspik** [comment]
@paweldudek Let me know what you think about this. :)

**Comment by paweldudek** [comment]
@Kaspik gosh, this took pretty long, sorry for that - there was some trouble with my access to this repo, but it's all resolved now 🎉

**Comment by Kaspik** [comment]
Thanks, we can now target main framework back again! 🎉

**Comment by Kaspik** [comment]
@paweldudek Shouldn't the latest release be marked as `0.1.0` instead of `0.0.4` ? Based on freeze in this PR...

**Pull request merged**
