### PR TITLE
Update danger and gemspec

### PR DESCRIPTION
**Pull request by Kaspik**
- bump danger to 6.0
- bump framework version to 0.0.4
- update dependencies

@paweldudek Sorry for another PR, I made a mistake previously and this should be complete. :)

Feel free to merge immediately and release new version.

### CODE REVIEW

**Comment by Kaspik** [comment]
@paweldudek Works on our CI as expected. :)

**Comment by Kaspik** [comment]
@paweldudek You wanna merge this?

**Comment by Kaspik** [comment]
@paweldudek One more time trying to reach out to you. :)

**Comment by gustavosaume** [comment]
any updates here? 😬

**Comment by Kaspik** [comment]
Feel free to use mine fork in the meantime... :)

**Comment by gustavosaume** [comment]
yup, I just forked it :)

**Comment by Kaspik** [comment]
@gustavosaume I'll bump it to Bundler 2.0.1 so if you are still using 1.x, use current master commit for your podfile. :)

**Comment by paweldudek** [comment]
Hey @Kaspik, @gustavosaume sorry for such a long turnaround. There's been some confusion with merge rights here, but it's all sorted out now! 🚀 

Thanks for your contribution, I've just pushed out a new version! 🙇

**Comment by Kaspik** [comment]
Thank you! I'll create another PR with the new bundler etc, but it might be major version update not only minor. :)

**Comment by Kaspik** [comment]
@paweldudek Just a note - missing a tag in Releases here on GitHub. :)

**Pull request merged**
