### PR TITLE
Add support for Danger 8.0

### PR DESCRIPTION
**Pull request by Kaspik**
- Update to support Danger 7.0
- Update other gem dependencies

### CODE REVIEW

**Comment by paweldudek** [comment]
#toomanyversions 😉

**Comment by Kaspik** [comment]
@paweldudek Hey, Danger 8.0 was released now and it has important fix for Github PR where inline comments had `strike-out` style incorrectly. Would you mind merging this and releasing new Github Tag? I already bumped the version too. :) Thanks!

**Comment by Kaspik** [comment]
... yeah, circle ci dropped ruby 2.3 version so Danger had to do it too, that's why major release. Sorry for that. 😕

**Comment by paweldudek** [comment]
No worries, thanks for updating this so quickly! 🙇

**Comment by Kaspik** [comment]
Sure thing, the bump there was my fault so it's my responsibility to fix it here too. 😄

**Comment by paweldudek** [comment]
And it's published now!

**Pull request merged**
