### PR TITLE
Update dependencies, bundler and gem version

### PR DESCRIPTION
**Pull request by Kaspik**
- udpated gemspec
- updated bundler
- update dependencies

After merging, this should be marked as 0.1.2 and not 0.0.4 as it still is.

### CODE REVIEW

**Comment by Kaspik** [comment]
@paweldudek Any update on merging this? :)

**Comment by Kaspik** [comment]
@paweldudek It would be nice if you could take a look on this and merge it.

**Comment by Kaspik** [comment]
It would be nice if anyone from Airhelp could take a look on this and merge it cc @groodt, @irvingwashington, @kszarek, @logx , @managr

**Comment by Kaspik** [comment]
Awesome, thanks @managr ! After merging, let's tag it and release it as 0.1.2 please so we all can switch back to this main repo. :)

**Comment by Kaspik** [comment]
@nglx Any chance this could go in?

**Comment by Kaspik** [comment]
Thank you @paweldudek ! If you will be able to also bump version and release it, it would be great. :)

**Comment by paweldudek** [comment]
Done & done. Enjoy!

**Pull request merged**
