### PR TITLE
Add support for Danger 7.0

### PR DESCRIPTION
**Pull request by Kaspik**
- Update to support Danger 7.0
- Update other gem dependencies

### CODE REVIEW

**Comment by Kaspik** [comment]
@paweldudek New version from yesterday is great for anyone with Danger 6.x, but new release of Danger 7.0 is not compatible. Here we go again. :)

**Comment by Kaspik** [comment]
@paweldudek I forgot to mubp the version for another release... 🤦 Could you please do it? Thanks!

**Comment by paweldudek** [comment]
Done, it's out! 🚀

**Comment by Kaspik** [comment]
... is it? :) https://github.com/AirHelp/danger-duplicate_localizable_strings/releases

**Comment by paweldudek** [comment]
I pushed out to Rubygems, tho admittedly I forgot about GH repo. That's updated now too!

**Comment by Kaspik** [comment]
Thank you Pawel, and have a nice weekend! :)

**Pull request merged**
